Finishing Assignment #20 React-Hook-Reducer
webprogramminghack/assignment-class20 pull request #2
Opened 2024-10-16 00:27 UTC by pramudios

please review

2025-01-13 05:23 UTC, webprogramminghack requested changes
Fix the code according to the comments provided

2025-01-13 05:23 UTC, webprogramminghack commented on src/components/UserFormWithReducer/UserFormWithReducer.tsx
> +      throw new Error(`Unhandled action type: ${_exhaustiveCheck}`);
Saya mendapatkan error
`Unexpected lexical declaration in case block.`

Silahkan tambahkan kurung kurawal, seperti yang sudah dijelaskan pada saat kelas, seperti ini
```
    default: {
      const _exhaustiveCheck: never = action;
      throw new Error(`Unhandled action type: ${_exhaustiveCheck}`);
    }
```

2025-01-13 05:23 UTC, webprogramminghack commented on src/components/UserFormWithReducer/UserFormWithReducer.tsx
> +        return _exhaustiveCheck;
Saya mendapatkan error
`Unexpected lexical declaration in case block.`

Silahkan tambahkan kurung kurawal, seperti yang sudah dijelaskan pada saat kelas, seperti ini
```
    default: {
      const _exhaustiveCheck: never = action;
      throw new Error(`Unhandled action type: ${_exhaustiveCheck}`);
    }
```

2025-01-13 05:23 UTC, webprogramminghack commented on src/components/CounterWithPrevious/CounterWithPrevious.tsx
>  export const CounterWithPrevious: React.FC = () => {
```suggestion
export const CounterWithPrevious: React.FC = () => {
```
saya mendapatkan error `'React' is not defined`

2025-01-13 05:23 UTC, webprogramminghack commented on src/components/UserFormWithReducer/UserFormWithReducer.tsx
> +      };
Sebagai pembelajaran, coba bandingkan dengan kode ini
```
    case 'UPDATE_NAME':
      return {
        ...state,
        name: action.payload,
      };
    case 'UPDATE_EMAIL':
      return {
        ...state,
        email: action.payload
      };
    case 'UPDATE_AGE':
      return {
        ...state,
        age: action.payload,
      };
```

2025-02-22 10:04 UTC, pramudios commented on src/components/UserFormWithReducer/UserFormWithReducer.tsx
> +      throw new Error(`Unhandled action type: ${_exhaustiveCheck}`);
Sudah diperbaiki

2025-02-22 10:05 UTC, pramudios commented on src/components/UserFormWithReducer/UserFormWithReducer.tsx
> +        return _exhaustiveCheck;
Sudah diperbaiki

2025-02-22 10:05 UTC, pramudios commented on src/components/CounterWithPrevious/CounterWithPrevious.tsx
>  export const CounterWithPrevious: React.FC = () => {
Sudah ditambahkan

2025-02-22 10:10 UTC, pramudios commented on src/components/UserFormWithReducer/UserFormWithReducer.tsx
> +      };
Sudah dicoba dengan menggunakan spread operator, spread operator berfungsi untuk menyalin semua properti state lama, lalu hanya mengganti yang diubah.

2025-02-24 05:48 UTC, webprogramminghack approved these changes
Assignment completed, good job

2025-02-24 05:48 UTC, closed without merging